// User Actions
export const AUDIT_USER_CREATED = 'USER_CREATED';
export const AUDIT_USER_UPDATED = 'USER_UPDATED';
export const AUDIT_USER_DELETED = 'USER_DELETED';
export const AUDIT_USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
export const AUDIT_USER_LOGIN_FAILURE = 'USER_LOGIN_FAILURE';

// Task Actions
export const AUDIT_TASK_CREATED = 'TASK_CREATED';
export const AUDIT_TASK_UPDATED = 'TASK_UPDATED';
export const AUDIT_TASK_DELETED = 'TASK_DELETED';
export const AUDIT_TASK_VIEWED = 'TASK_VIEWED';
export const AUDIT_TASKS_LISTED = 'TASKS_LISTED';

// Organization Actions
export const AUDIT_ORGANIZATION_CREATED = 'ORGANIZATION_CREATED';
export const AUDIT_ORGANIZATION_UPDATED = 'ORGANIZATION_UPDATED';
export const AUDIT_ORGANIZATION_DELETED = 'ORGANIZATION_DELETED';

// General/Security Actions
export const AUDIT_ACCESS_DENIED = 'ACCESS_DENIED';
